/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier */

#ifndef _Included_pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier
#define _Included_pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier_init
(JNIEnv *, jclass);

/*
 * Class:     pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier_load
(JNIEnv *, jclass, jstring);

/*
 * Class:     pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier
 * Method:    train
 * Signature: ([J[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier_train
(JNIEnv *, jclass, jlongArray, jintArray, jstring);

/*
 * Class:     pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier
 * Method:    predict
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_pl_polsl_wkiro_facerecognizer_classifier_FaceClassifier_predict
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
